

services:
  # Serviço 1: Aplicação PHP (Laravel)
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # O 'app' (Cliente) lê o .env (Isto está CORRETO)
    env_file:  
      - .env
    # Adicionado 'depends_on' para esperar o 'db'
    depends_on:
      - db
      - python
    networks:
      - app-network

  # Serviço 2: Servidor Web (Nginx)
  nginx:
    image: nginx:1.19-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # Serviço 3: Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:

      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Use a senha do .env
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    
    # Diz ao 'db' (Servidor) para ler o .env também
    env_file:
      - .env
    
    volumes:
      - db-data:/var/lib/mysql # Volume isolado (CORRETO)
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Serviço 4: Ambiente Python para os Agentes de IA
  python:
    build:
      context: ./backend # Onde o código (main.py, etc.) está
      dockerfile: ../.docker/python/Dockerfile # Onde o Dockerfile está (um nível acima, na raiz)
    container_name: python_agents
    working_dir: /app
    env_file: 
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    ports:
      - "8001:8000"

# Define o volume isolado para o banco
volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge